# Generated by Django 4.2.17 on 2026-03-27 21:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Short stable identifier (uppercase). Used in reporting and billing.', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('CLINIC', 'Clinic'), ('HOSPITAL', 'Hospital'), ('LABORATORY', 'Partner Laboratory'), ('MEDICAL_CENTER', 'Medical Center'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('default_billing_mode', models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('ON_ACCOUNT', 'On Account (invoiced)'), ('PER_REQUEST', 'Per Request')], help_text='Default billing mode for requests from this partner.', max_length=15, null=True)),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, help_text='Payment terms in days (e.g. 30, 60). Used by future invoicing module.', null=True)),
                ('billing_notes', models.TextField(blank=True, default='', help_text='Internal notes on billing arrangements.')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Partner Organization',
                'verbose_name_plural': 'Partner Organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization_type', 'is_active'], name='partners_pa_organiz_778ecd_idx')],
            },
        ),
    ]
