# Generated by Django 4.2.17 on 2026-04-11 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_examdefinition_options_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerExamPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_price', models.DecimalField(decimal_places=4, help_text='Negotiated unit price applied to requests from this partner.', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about the negotiation context or rationale.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('exam_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_prices', to='catalog.examdefinition')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_prices', to='partners.partnerorganization')),
            ],
            options={
                'verbose_name': 'Partner Exam Price',
                'verbose_name_plural': 'Partner Exam Prices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'is_active'], name='partners_pa_partner_aa2754_idx'), models.Index(fields=['exam_definition', 'is_active'], name='partners_pa_exam_de_74cc81_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='partnerexamprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('partner', 'exam_definition'), name='unique_active_partner_exam_price'),
        ),
        migrations.AddConstraint(
            model_name='partnerexamprice',
            constraint=models.CheckConstraint(check=models.Q(('agreed_price__gte', 0)), name='partner_exam_price_non_negative'),
        ),
    ]
