# Generated by Django 4.2.17 on 2026-04-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partnerorganization_invoice_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='invoice_vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT percentage applied on the subtotal after discount (e.g. 18.00 for 18%). Snapshotted at invoice generation.', max_digits=5, null=True),
        ),
    ]
