# Generated by Django 4.2.17 on 2026-04-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partnerorganization_invoice_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorganization',
            name='invoice_vat_rate',
        ),
    ]
