# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='ACTIVE', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, help_text='The threshold/limit at scan time (e.g. minimum_threshold).', max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, help_text='The observed value at scan time (e.g. available qty, days to expiry).', max_digits=12, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Alert',
                'verbose_name_plural': 'Inventory Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
