# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Null when auto-resolved by scan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='stock_item',
            field=models.ForeignKey(help_text='The stock item this alert refers to.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.stockitem'),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='stock_lot',
            field=models.ForeignKey(blank=True, help_text='Set for lot-level alerts (EXPIRING_SOON, EXPIRED).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.stocklot'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['status', 'severity'], name='alerts_inve_status_770748_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['alert_type', 'status'], name='alerts_inve_alert_t_e9502d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['stock_item', 'alert_type', 'status'], name='alerts_inve_stock_i_657189_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'ACKNOWLEDGED']), ('stock_lot__isnull', True)), fields=('alert_type', 'stock_item'), name='unique_open_item_alert'),
        ),
        migrations.AddConstraint(
            model_name='inventoryalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'ACKNOWLEDGED']), ('stock_lot__isnull', False)), fields=('alert_type', 'stock_lot'), name='unique_open_lot_alert'),
        ),
    ]
