# Generated by Django 4.2.17 on 2026-04-14 10:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_name', models.CharField(blank=True, default='', max_length=255)),
                ('lab_subtitle', models.CharField(blank=True, default='', help_text='e.g. "Medical Analysis Laboratory"', max_length=255)),
                ('logo_file_key', models.CharField(blank=True, default='', help_text='Internal storage key for the laboratory logo image.', max_length=500)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('signature_file_key', models.CharField(blank=True, default='', help_text='Internal storage key for the validator signature/stamp image.', max_length=500)),
                ('legal_footer', models.TextField(blank=True, default='', help_text='Confidentiality / legal text printed at the bottom of reports.')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_lab_address', models.BooleanField(default=True)),
                ('show_prescriber', models.BooleanField(default=True)),
                ('show_collection_datetime', models.BooleanField(default=True)),
                ('show_patient_age', models.BooleanField(default=True)),
                ('show_patient_sex', models.BooleanField(default=True)),
                ('show_exam_technique', models.BooleanField(default=True)),
                ('show_reference_ranges', models.BooleanField(default=True)),
                ('show_patient_comments', models.BooleanField(default=True)),
                ('show_final_conclusion', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=True)),
                ('show_legal_footer', models.BooleanField(default=True)),
                ('show_abnormal_flags', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lab Settings',
                'verbose_name_plural': 'Lab Settings',
            },
        ),
    ]
