# Generated by Django 4.2.17 on 2026-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='External URL fallback when no file has been uploaded (display only).'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='logo_file_key',
            field=models.CharField(blank=True, default='', help_text='Internal storage key for the uploaded laboratory logo image.', max_length=500),
        ),
    ]
