# Generated by Django 4.2.17 on 2026-04-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0005_report_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='default_invoice_vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default VAT percentage applied on invoices (e.g. 18.00 for 18%). Snapshotted at invoice generation time.', max_digits=5, null=True),
        ),
    ]
