# Generated by Django 4.2.17 on 2026-04-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0006_labsettings_default_invoice_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='financial_document_mode',
            field=models.CharField(choices=[('INVOICE_ONLY', 'Invoice only'), ('STATEMENT_ONLY', 'Financial statement only'), ('BOTH', 'Both invoice and financial statement')], default='INVOICE_ONLY', help_text='Controls which financial document types this lab can generate.', max_length=30),
        ),
    ]
