# Generated by Django 4.2.17 on 2026-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0008_labsettings_result_pdf_password_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='lab_secret_code',
            field=models.CharField(blank=True, default='', help_text='Random code auto-generated per lab. Used as a component in PDF password derivation. Regenerable by lab admin.', max_length=6),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='result_pdf_password_mode',
            field=models.CharField(choices=[('PATIENT_DOB', 'Patient date of birth (YYYYMMDD)'), ('PATIENT_PHONE', 'Patient phone (digits only)'), ('REQUEST_REFERENCE', 'Request public reference'), ('DOB_PLUS_PHONE_SUFFIX', 'DOB + last 4 digits of phone'), ('DOB_PHONE_SECRET', 'DOB + phone suffix + lab secret code')], default='DOB_PHONE_SECRET', max_length=30),
        ),
    ]
