# Generated by Django 4.2.17 on 2026-04-23 08:12

from django.db import migrations, models


def truncate_secret_codes(apps, schema_editor):
    LabSettings = apps.get_model('lab_settings', 'LabSettings')
    for row in LabSettings.objects.all():
        if len(row.lab_secret_code) > 2:
            row.lab_secret_code = row.lab_secret_code[:2]
            row.save(update_fields=['lab_secret_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0009_labsettings_lab_secret_code_and_more'),
    ]

    operations = [
        migrations.RunPython(truncate_secret_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='labsettings',
            name='lab_secret_code',
            field=models.CharField(blank=True, default='', help_text='2-character code auto-generated per lab. Used as a suffix in PDF password derivation. Regenerable by lab admin.', max_length=2),
        ),
    ]
