# Generated by Django 4.2.17 on 2026-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0010_alter_labsettings_lab_secret_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='notification_enable_email',
            field=models.BooleanField(default=False, help_text='Enable email notification to patients (not yet implemented).'),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='notification_enable_secure_link',
            field=models.BooleanField(default=True, help_text='Allow generating secure access links for patient results.'),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='notification_enable_sms',
            field=models.BooleanField(default=False, help_text='Enable SMS notification to patients (not yet implemented).'),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='notification_enable_whatsapp_share',
            field=models.BooleanField(default=True, help_text='Show WhatsApp share option for patient result links.'),
        ),
    ]
