# Generated by Django 4.2.17 on 2026-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0011_labsettings_notification_enable_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='notification_enable_cytova',
            field=models.BooleanField(default=True, help_text='Allow sharing patient results into the global Cytova patient portal (Notify Cytova). When disabled, the endpoint refuses with CYTOVA_CHANNEL_DISABLED and the lab UI hides the channel.'),
        ),
    ]
