# Generated by Django 4.2.17 on 2026-05-02 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0012_labsettings_notification_enable_cytova'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='extra_label_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of extra labels appended to every batch on top of the per-family labels. Default 2 preserves the pre-rollout behaviour; set to 0 to disable.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='label_numbering_mode',
            field=models.CharField(choices=[('PER_FAMILY', 'Per family'), ('SAME_REQUEST_NUMBER', 'Same request number')], default='PER_FAMILY', help_text="How a request's labels share (or not) a numeric label code. Defaults to PER_FAMILY (current behaviour).", max_length=24),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='label_sequence_reset_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text="How often the tenant's label sequence counter resets. Defaults to MONTHLY (current behaviour).", max_length=10),
        ),
    ]
