# Generated by Django 4.2.17 on 2026-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_settings', '0014_labsettings_patient_result_email_body_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='internal_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for internal-workflow emails (biologist review-ready, technician rejection). When False, no workflow email is sent regardless of the per-event flags below.'),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='notify_result_rejected_enabled',
            field=models.BooleanField(default=True, help_text='If False, technician rejection emails are suppressed even when the master switch is on.'),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='notify_review_ready_enabled',
            field=models.BooleanField(default=True, help_text='If False, biologist review-ready emails are suppressed even when the master switch is on.'),
        ),
    ]
