# Generated by Django 4.2.17 on 2026-05-05 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUPPORT', 'Support'), ('BILLING_ADMIN', 'Billing Admin'), ('TECH_ADMIN', 'Tech Admin'), ('READ_ONLY_AUDITOR', 'Read-only Auditor')], default='SUPPORT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Admin User',
                'verbose_name_plural': 'Platform Admin Users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('PLATFORM_ADMIN_LOGIN', 'Platform Admin Login'), ('PLATFORM_ADMIN_LOGIN_FAILED', 'Platform Admin Login Failed')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='platform_admin.platformadminuser')),
            ],
            options={
                'verbose_name': 'Platform Admin Audit Log',
                'verbose_name_plural': 'Platform Admin Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='platform_ad_action_03a41e_idx'), models.Index(fields=['actor', 'created_at'], name='platform_ad_actor_i_09e43c_idx')],
            },
        ),
    ]
