# Generated by Django 4.2.17 on 2026-05-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformadminauditlog',
            name='action',
            field=models.CharField(choices=[('PLATFORM_ADMIN_LOGIN', 'Platform Admin Login'), ('PLATFORM_ADMIN_LOGIN_FAILED', 'Platform Admin Login Failed'), ('PLATFORM_TENANT_LIST_VIEWED', 'Platform Tenant List Viewed'), ('PLATFORM_TENANT_DETAIL_VIEWED', 'Platform Tenant Detail Viewed')], db_index=True, max_length=40),
        ),
    ]
