# Generated by Django 4.2.17 on 2026-05-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_alter_platformadminauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformadminauditlog',
            name='action',
            field=models.CharField(choices=[('PLATFORM_ADMIN_LOGIN', 'Platform Admin Login'), ('PLATFORM_ADMIN_LOGIN_FAILED', 'Platform Admin Login Failed'), ('PLATFORM_TENANT_LIST_VIEWED', 'Platform Tenant List Viewed'), ('PLATFORM_TENANT_DETAIL_VIEWED', 'Platform Tenant Detail Viewed'), ('PLATFORM_TENANT_SUSPENDED', 'Platform Tenant Suspended'), ('PLATFORM_TENANT_REACTIVATED', 'Platform Tenant Reactivated'), ('PLATFORM_TENANT_TRIAL_EXTENDED', 'Platform Tenant Trial Extended'), ('PLATFORM_TENANT_PLAN_CHANGED', 'Platform Tenant Plan Changed'), ('PLATFORM_PATIENT_LIST_VIEWED', 'Platform Patient List Viewed'), ('PLATFORM_PATIENT_DETAIL_VIEWED', 'Platform Patient Detail Viewed'), ('PLATFORM_PATIENT_DEACTIVATED', 'Platform Patient Deactivated'), ('PLATFORM_PATIENT_REACTIVATED', 'Platform Patient Reactivated'), ('PLATFORM_DASHBOARD_VIEWED', 'Platform Dashboard Viewed')], db_index=True, max_length=40),
        ),
    ]
