# Generated by Django 4.2.17 on 2026-03-27 15:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Stock Category',
                'verbose_name_plural': 'Stock Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(help_text='Unit of measure (e.g. mL, box, vial, tube, piece).', max_length=50)),
                ('minimum_threshold', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Low-stock alert threshold. An alert fires when the sum of non-exhausted lot quantities falls below this value.', max_digits=12)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Suggested order quantity (future procurement module).', max_digits=12, null=True)),
                ('main_supplier_name', models.CharField(blank=True, default='', help_text='Will become a FK to Supplier once that module is implemented.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(help_text='Manufacturer or internal lot / batch number.', max_length=100)),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Leave blank for non-expiring items (equipment, etc.).', null=True)),
                ('supplier_name', models.CharField(blank=True, default='', help_text='Supplier for this specific delivery.', max_length=255)),
                ('initial_quantity', models.DecimalField(decimal_places=4, help_text='Quantity received at lot creation. Immutable after first save.', max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=4, help_text='Running total. Maintained by StockLotService — do not write directly.', max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per unit for this delivery (optional).', max_digits=12, null=True)),
                ('received_at', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_exhausted', models.BooleanField(db_index=True, default=False, help_text='True when current_quantity <= 0.')),
            ],
            options={
                'verbose_name': 'Stock Lot',
                'verbose_name_plural': 'Stock Lots',
                'ordering': ['-received_at', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In (received from supplier)'), ('OUT', 'Stock Out (consumed in operations)'), ('ADJUSTMENT_IN', 'Adjustment In (inventory recount +)'), ('ADJUSTMENT_OUT', 'Adjustment Out (inventory recount −)'), ('LOSS', 'Loss (damage / spillage / expiry)')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_before', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reason', models.TextField(blank=True, default='', help_text='Required for LOSS, ADJUSTMENT_IN, ADJUSTMENT_OUT.')),
                ('reference', models.CharField(blank=True, default='', help_text='Soft link to another entity (e.g. REQ-2024-ABCD1234).', max_length=100)),
                ('reference_type', models.CharField(blank=True, default='', help_text='Type of referenced entity (e.g. AnalysisRequest, PurchaseOrder).', max_length=50)),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.stocklot')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-performed_at'],
            },
        ),
    ]
