# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='stock.stockitem'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.stockcategory'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot', 'performed_at'], name='stock_stock_lot_id_c4e119_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'performed_at'], name='stock_stock_movemen_19ba40_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['item', 'is_exhausted'], name='stock_stock_item_id_25916f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['expiry_date'], name='stock_stock_expiry__4916e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('item', 'lot_number'), name='unique_lot_number_per_item'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['category', 'is_active'], name='stock_stock_categor_93e95d_idx'),
        ),
    ]
