# Generated by Django 4.2.17 on 2026-03-28 00:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in base currency. Informational until billing is implemented.', max_digits=10, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price in base currency. Informational until billing is implemented.', max_digits=10, null=True)),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Default trial duration in days when a lab signs up on this plan.')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Feature flags / limits for this plan (e.g. max_users, max_exams).')),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], db_index=True, default='TRIAL', max_length=15)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this subscription began.')),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of the current billing period. Null for open-ended.', null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, db_index=True, help_text='When the trial expires. Null if not a trial.', null=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the subscription transitioned from TRIAL to ACTIVE.', null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, default='', help_text='Who cancelled: "admin", "platform", or "system".', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='tenants_sub_tenant__7ec0ec_idx'), models.Index(fields=['status', 'trial_end_date'], name='tenants_sub_status_5c4bb7_idx')],
            },
        ),
    ]
