# Generated by Django 4.2.17 on 2026-03-28 10:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ACTIVATE', 'Activate'), ('SUSPEND', 'Suspend'), ('CANCEL', 'Cancel'), ('DEACTIVATE', 'Deactivate'), ('PLAN_CHANGE', 'Plan Change')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Platform Audit Log',
                'verbose_name_plural': 'Platform Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
