# Generated by Django 4.2.17 on 2026-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_platformauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_days',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, this plan is visible on the public pricing page.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this plan is used for automatic trial subscriptions on signup.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Trial duration in days. Required when is_trial=True. Null for paid plans.', null=True),
        ),
    ]
