# Generated by Django 4.2.17 on 2026-04-30 21:53

import apps.patient_portal.managers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Account',
                'verbose_name_plural': 'Patient Accounts',
                'db_table': 'patient_portal_account',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.patient_portal.managers.PatientAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cytova_patient_id', models.CharField(db_index=True, help_text='Public-facing Cytova Patient ID (CV-XXXX-XXXX).', max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='patient_portal.patientaccount')),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'db_table': 'patient_portal_profile',
            },
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_version', models.CharField(max_length=20)),
                ('privacy_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patient_portal.patientaccount')),
            ],
            options={
                'verbose_name': 'Patient Consent',
                'verbose_name_plural': 'Patient Consents',
                'db_table': 'patient_portal_consent',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['account', '-accepted_at'], name='patient_por_account_368906_idx')],
            },
        ),
    ]
