# Generated by Django 4.2.17 on 2026-04-30 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to='patient_portal.patientaccount')),
            ],
            options={
                'verbose_name': 'Patient Email Verification Token',
                'verbose_name_plural': 'Patient Email Verification Tokens',
                'db_table': 'patient_portal_email_verification_token',
                'indexes': [models.Index(fields=['account', 'is_used'], name='patient_por_account_767d92_idx')],
            },
        ),
    ]
