# Generated by Django 4.2.17 on 2026-05-01 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_patientemailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSharedResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('DIRECT', 'Direct'), ('PARTNER', 'Partner')], default='DIRECT', max_length=10)),
                ('source_name', models.CharField(help_text='Snapshot of the lab name (or partner name) at share time.', max_length=255)),
                ('request_reference', models.CharField(blank=True, default='', help_text='Snapshot of the request public reference / number — what the patient should quote when contacting the lab.', max_length=64)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('result_available_date', models.DateField(blank=True, null=True)),
                ('created_by_lab', models.CharField(blank=True, default='', help_text='Optional snapshot of the staff member or lab identity that initiated the share.', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_results', to='patient_portal.patientaccount')),
            ],
            options={
                'verbose_name': 'Patient Shared Result',
                'verbose_name_plural': 'Patient Shared Results',
                'db_table': 'patient_portal_shared_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientSharedResultFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_token', models.CharField(db_index=True, editable=False, help_text='Opaque random reference used by the future patient portal download endpoint.', max_length=64, unique=True)),
                ('filename', models.CharField(help_text='Suggested download filename for the patient browser.', max_length=255)),
                ('storage_key', models.CharField(blank=True, default='', help_text='Snapshot of the underlying file storage key. Internal — patients never see this. Allows the future download endpoint to locate the original PDF without crossing into a tenant database table.', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patient_portal.patientsharedresult')),
            ],
            options={
                'verbose_name': 'Patient Shared Result File',
                'verbose_name_plural': 'Patient Shared Result Files',
                'db_table': 'patient_portal_shared_result_file',
            },
        ),
        migrations.AddIndex(
            model_name='patientsharedresult',
            index=models.Index(fields=['patient_account', '-created_at'], name='patient_por_patient_5b20d8_idx'),
        ),
    ]
