# Generated by Django 4.2.17 on 2026-05-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0003_patientsharedresult_patientsharedresultfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsharedresult',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HIDDEN_BY_PATIENT', 'Hidden by patient'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
