# Generated by Django 4.2.17 on 2026-05-01 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0004_alter_patientsharedresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsharedresult',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='email_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='email_notification_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='first_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='revoked_by_lab',
            field=models.CharField(blank=True, default='', help_text='Snapshot of who/what triggered the revocation (staff email or lab identity). Free text — the patient never sees this.', max_length=255),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='source_request_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the originating ``AnalysisRequest.id`` in the lab tenant schema. Soft reference (no FK — the tables live in different schemas).', null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='source_tenant_schema',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the lab tenant schema name that produced this share. Used by the lab-side revoke endpoint to scope its lookup; never exposed to the patient.', max_length=64),
        ),
        migrations.CreateModel(
            name='PatientPortalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PATIENT_RESULT_SHARED', 'Result shared by lab'), ('PATIENT_RESULT_DOWNLOADED', 'Result downloaded by patient'), ('PATIENT_RESULT_HIDDEN_BY_PATIENT', 'Result hidden by patient'), ('PATIENT_RESULT_REVOKED_BY_LAB', 'Share revoked by lab')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('patient_account', models.ForeignKey(blank=True, help_text='Set null on account deletion so the audit row survives — needed for forensic continuity even when the actor account is gone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='patient_portal.patientaccount')),
            ],
            options={
                'verbose_name': 'Patient Portal Audit Log',
                'verbose_name_plural': 'Patient Portal Audit Logs',
                'db_table': 'patient_portal_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_account', '-created_at'], name='patient_por_patient_cec04b_idx'), models.Index(fields=['action', '-created_at'], name='patient_por_action_b5ef95_idx')],
            },
        ),
    ]
