# Generated by Django 4.2.17 on 2026-05-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0005_patientsharedresult_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsharedresultfile',
            name='patient_storage_key',
            field=models.CharField(blank=True, default='', help_text='Path of the portal-owned copy of the PDF. Created at share time via ``copy_file``. Always preferred by the download endpoint over the lab-side snapshot.', max_length=500),
        ),
        migrations.AddField(
            model_name='patientsharedresultfile',
            name='storage_origin',
            field=models.CharField(choices=[('LAB', 'Lab'), ('PATIENT', 'Patient')], db_index=True, default='LAB', help_text='Which storage location backs this row. ``PATIENT`` means the file was successfully copied into the patient portal storage; ``LAB`` means the patient is still served from the original tenant location (legacy rows or copy-failure fallback).', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientsharedresultfile',
            name='storage_key',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the LAB-side file storage key. Internal — patients never see this. Used as a fallback when the patient-side copy is unavailable (e.g. legacy rows or copy-time failure).', max_length=500),
        ),
    ]
