# Generated by Django 4.2.17 on 2026-05-01 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0006_patientsharedresultfile_patient_storage_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOutstandingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, help_text='JWT ID claim — the only durable identifier we store. Compared against the ``jti`` in the bearer token on every request.', max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('ACCESS', 'Access'), ('REFRESH', 'Refresh')], max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_tokens', to='patient_portal.patientaccount')),
            ],
            options={
                'verbose_name': 'Patient Outstanding Token',
                'verbose_name_plural': 'Patient Outstanding Tokens',
                'db_table': 'patient_portal_outstanding_token',
            },
        ),
        migrations.CreateModel(
            name='PatientBlacklistedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blacklisted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='patient_portal.patientoutstandingtoken')),
            ],
            options={
                'verbose_name': 'Patient Blacklisted Token',
                'verbose_name_plural': 'Patient Blacklisted Tokens',
                'db_table': 'patient_portal_blacklisted_token',
            },
        ),
        migrations.AddIndex(
            model_name='patientoutstandingtoken',
            index=models.Index(fields=['patient_account', 'expires_at'], name='patient_por_patient_14fa16_idx'),
        ),
    ]
