# Generated by Django 4.2.17 on 2026-05-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0007_patientoutstandingtoken_patientblacklistedtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsharedresult',
            name='is_current_for_patient',
            field=models.BooleanField(db_index=True, default=True, help_text='True iff this is the latest version the lab shared with this patient for this source request. Toggled to False by the share service when a newer version is shared. Independent of ``status`` — a row that is current for the patient may still be REVOKED, in which case the patient view filters it out anyway.'),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, help_text='Snapshot of when the underlying lab report version was generated. Distinct from ``shared_at`` because a version may be generated long before it is actually shared.', null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='report_version_number',
            field=models.PositiveIntegerField(blank=True, help_text='Lab-side report version_number snapshotted at share time.', null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='shared_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this version was actively shared/notified to the patient. Coincides with ``created_at`` for new rows; kept as a separate column so the patient versions API has a semantic, channel-agnostic timestamp to expose.', null=True),
        ),
        migrations.AddField(
            model_name='patientsharedresult',
            name='shared_channel',
            field=models.CharField(blank=True, choices=[('CYTOVA', 'Cytova'), ('EMAIL', 'Email'), ('SHARE_LINK', 'Share link'), ('MANUAL', 'Manual')], default='', help_text='Which channel materialised this shared version. ``CYTOVA`` is the only writer in Phase 1.', max_length=15),
        ),
        migrations.AlterField(
            model_name='patientportalauditlog',
            name='action',
            field=models.CharField(choices=[('PATIENT_RESULT_SHARED', 'Result shared by lab'), ('PATIENT_RESULT_DOWNLOADED', 'Result downloaded by patient'), ('PATIENT_RESULT_HIDDEN_BY_PATIENT', 'Result hidden by patient'), ('PATIENT_RESULT_REVOKED_BY_LAB', 'Share revoked by lab'), ('PATIENT_VERSION_SHARED', 'Version shared with patient'), ('PATIENT_VERSION_SUPERSEDED', 'Earlier shared version superseded')], db_index=True, max_length=40),
        ),
    ]
