# Generated by Django 4.2.17 on 2026-05-12 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0004_result_values'),
        ('analysis_requests', '0023_analysisrequestitem_parameter_ids_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REQUEST_READY_FOR_REVIEW', 'Request ready for biological review'), ('RESULT_REJECTED', 'Result rejected by biologist')], db_index=True, max_length=40)),
                ('recipient_email', models.EmailField(help_text='Email-at-attempt-time snapshot. NEVER a patient address — recipients are resolved exclusively from StaffUser.', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending delivery'), ('SENT', 'Delivered'), ('FAILED', 'Delivery failed')], db_index=True, default='PENDING', max_length=10)),
                ('dedupe_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_internal_notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_notifications', to='analysis_requests.analysisrequest')),
                ('result_version', models.ForeignKey(blank=True, help_text='Only set on RESULT_REJECTED events; null for request-level events.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_notifications', to='results.resultversion')),
            ],
            options={
                'verbose_name': 'Internal Notification Log',
                'verbose_name_plural': 'Internal Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='internal_no_event_t_6cb557_idx'), models.Index(fields=['request', 'event_type'], name='internal_no_request_f5a3fd_idx')],
            },
        ),
    ]
