# Generated by Django 4.2.17 on 2026-03-27 15:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated: PO-{YYYY}-{8-char UUID}.', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25)),
                ('expected_delivery_date', models.DateField(blank=True, db_index=True, help_text='Requested or agreed delivery date.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Set when order is force-closed with outstanding quantities.', null=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=4, help_text='Quantity requested from the supplier.', max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Running total received. Maintained by ReceptionService.', max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Negotiated price per unit for this order.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_at', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date the goods physically arrived.')),
                ('notes', models.TextField(blank=True, default='')),
                ('has_discrepancy', models.BooleanField(db_index=True, default=False, help_text='True if any item was over- or short-delivered.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='suppliers.purchaseorder')),
            ],
            options={
                'verbose_name': 'Reception',
                'verbose_name_plural': 'Receptions',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Company name. Must be unique within the tenant.', max_length=255, unique=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_quantity', models.DecimalField(decimal_places=4, help_text='Quantity physically received in this event.', max_digits=12)),
                ('lot_number', models.CharField(help_text='Manufacturer or internal lot/batch number for this delivery.', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank for non-expiring items.', null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Actual cost per unit for this delivery. Defaults to order unit_price.', max_digits=12, null=True)),
                ('discrepancy_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Signed discrepancy: received − remaining at time of reception. Positive = over-delivered, negative = accepted short delivery.', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_items', to='suppliers.purchaseorderitem')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.reception')),
                ('stock_lot', models.OneToOneField(blank=True, help_text='The StockLot created by this reception item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_item', to='stock.stocklot')),
            ],
            options={
                'verbose_name': 'Reception Item',
                'verbose_name_plural': 'Reception Items',
                'ordering': ['created_at'],
            },
        ),
    ]
