# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(blank=True, db_index=True, default='', help_text='Auto-generated human-readable identifier.', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis Request',
                'verbose_name_plural': 'Analysis Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('execution_mode', models.CharField(choices=[('INTERNAL', 'Internal'), ('SUBCONTRACTED', 'Subcontracted'), ('REJECTED', 'Rejected')], db_index=True, default='INTERNAL', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('external_partner_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('billed_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Analysis Request Item',
                'verbose_name_plural': 'Analysis Request Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamTraceability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_received_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traceability', to='analysis_requests.analysisrequestitem')),
            ],
            options={
                'verbose_name': 'Exam Traceability',
                'verbose_name_plural': 'Exam Traceability Records',
            },
        ),
    ]
