# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtraceability',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtraceability',
            name='sample_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequestitem',
            name='analysis_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analysis_requests.analysisrequest'),
        ),
        migrations.AddField(
            model_name='analysisrequestitem',
            name='exam_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='catalog.examdefinition'),
        ),
        migrations.AddField(
            model_name='analysisrequestitem',
            name='pricing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_snapshots', to='catalog.pricingrule'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analysis_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_requests', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='analysisrequestitem',
            constraint=models.UniqueConstraint(fields=('analysis_request', 'exam_definition'), name='unique_exam_per_request'),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['patient', 'status'], name='analysis_re_patient_50e07f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['status', 'created_at'], name='analysis_re_status_47fe8a_idx'),
        ),
    ]
