# Generated by Django 4.2.17 on 2026-03-27 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('analysis_requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='billing_mode',
            field=models.CharField(choices=[('DIRECT_PAYMENT', 'Direct Payment'), ('PARTNER_BILLING', 'Partner Billing')], db_index=True, default='DIRECT_PAYMENT', help_text='How this request will be billed.', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='external_reference',
            field=models.CharField(blank=True, default='', help_text='Reference number from the partner (e.g. their internal order ID).', max_length=100),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='partner_organization',
            field=models.ForeignKey(blank=True, help_text='Required when source_type is PARTNER_ORGANIZATION.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_requests', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='source_notes',
            field=models.TextField(blank=True, default='', help_text='Free-text notes related to the request source or billing.'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='source_type',
            field=models.CharField(choices=[('DIRECT_PATIENT', 'Direct Patient'), ('PARTNER_ORGANIZATION', 'Partner Organization')], db_index=True, default='DIRECT_PATIENT', help_text='Where this request originated from.', max_length=25),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['source_type', 'partner_organization'], name='analysis_re_source__43a73a_idx'),
        ),
    ]
