# Generated by Django 4.2.17 on 2026-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_requests', '0004_item_pricing_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequestitem',
            name='price_source',
            field=models.CharField(choices=[('DEFAULT_PRICE', 'Default Price'), ('PARTNER_AGREED_PRICE', 'Partner Agreed Price'), ('PRICING_RULE', 'Pricing Rule'), ('MANUAL_OVERRIDE', 'Manual Override')], default='DEFAULT_PRICE', help_text='How the billed price was determined.', max_length=20),
        ),
    ]
