# Generated by Django 4.2.17 on 2026-04-11 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_requests', '0005_alter_analysisrequestitem_price_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLabelBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('label_count', models.PositiveSmallIntegerField(help_text='Total labels in this batch (distinct families + fixed extras).')),
                ('family_count', models.PositiveSmallIntegerField(help_text='Distinct exam families counted at generation time (audit).')),
                ('pdf_file_key', models.CharField(blank=True, default='', help_text='Internal storage key for the rendered PDF. Never exposed to clients as-is.', max_length=500)),
                ('analysis_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='label_batch', to='analysis_requests.analysisrequest')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_label_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Label Batch',
                'verbose_name_plural': 'Request Label Batches',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_value', models.CharField(db_index=True, help_text='System-wide unique identifier printed on the label and scanned in workflow.', max_length=64, unique=True)),
                ('label_index', models.PositiveSmallIntegerField(help_text='1-based position of this label within the batch.')),
                ('family_name', models.CharField(blank=True, default='', help_text='Exam family this label is pinned to; empty for the fixed extras.', max_length=150)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='analysis_requests.requestlabelbatch')),
            ],
            options={
                'verbose_name': 'Request Label',
                'verbose_name_plural': 'Request Labels',
                'ordering': ['batch', 'label_index'],
                'indexes': [models.Index(fields=['batch', 'label_index'], name='analysis_re_batch_i_f05671_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='requestlabel',
            constraint=models.UniqueConstraint(fields=('batch', 'label_index'), name='unique_label_index_per_batch'),
        ),
    ]
