# Generated by Django 4.2.17 on 2026-04-11 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_requests', '0006_requestlabelbatch_requestlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequestitem',
            name='collected_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the specimen for this item was collected.', null=True),
        ),
        migrations.AddField(
            model_name='analysisrequestitem',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who marked the item as collected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequestitem',
            name='collection_notes',
            field=models.TextField(blank=True, default='', help_text='Optional operational notes captured at collection time.'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('COLLECTION_IN_PROGRESS', 'Collection In Progress'), ('IN_ANALYSIS', 'In Analysis'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='analysisrequestitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Collection'), ('COLLECTED', 'Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
