# Generated by Django 4.2.17 on 2026-04-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_requests', '0008_alter_analysisrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('COLLECTION_IN_PROGRESS', 'Collection In Progress'), ('IN_ANALYSIS', 'In Analysis'), ('AWAITING_REVIEW', 'Awaiting Review'), ('RETEST_REQUIRED', 'Retest Required'), ('VALIDATED', 'Validated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='analysisrequestitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Collection'), ('COLLECTED', 'Collected'), ('RESULT_ENTERED', 'Result Entered'), ('UNDER_REVIEW', 'Under Review'), ('VALIDATED', 'Validated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
