# Generated by Django 4.2.17 on 2026-04-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_requests', '0009_alter_analysisrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('COLLECTION_IN_PROGRESS', 'Collection In Progress'), ('IN_ANALYSIS', 'In Analysis'), ('AWAITING_REVIEW', 'Awaiting Review'), ('RETEST_REQUIRED', 'Retest Required'), ('READY_FOR_RELEASE', 'Ready For Release'), ('VALIDATED', 'Validated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25),
        ),
    ]
