# Generated by Django 4.2.17 on 2026-04-14 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_requests', '0010_alter_analysisrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='final_conclusion',
            field=models.TextField(blank=True, default='', help_text='Biologist conclusion included on the final patient report.'),
        ),
        migrations.CreateModel(
            name='AnalysisRequestReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('pdf_file_key', models.CharField(blank=True, default='', help_text='Internal storage key for the rendered PDF. Never exposed to clients.', max_length=500)),
                ('analysis_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='analysis_requests.analysisrequest')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Request Report',
                'verbose_name_plural': 'Analysis Request Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
