# Generated by Django 4.2.17 on 2026-04-23 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_refactor_identification'),
        ('analysis_requests', '0014_public_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('report_file_key', models.CharField(help_text='Snapshot of the pdf_file_key at token creation time.', max_length=500)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('analysis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='analysis_requests.analysisrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_access_tokens', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Result Access Token',
                'verbose_name_plural': 'Result Access Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
