# Generated by Django 4.2.17 on 2026-04-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_requests', '0015_resultaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultaccesstoken',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultaccesstoken',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultaccesstoken',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
