# Generated by Django 4.2.17 on 2026-04-27 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_requests', '0016_resultaccesstoken_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='last_patient_notification_channel',
            field=models.CharField(blank=True, default='', help_text='Channel used for the most recent successful notification (e.g. "EMAIL").', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='notification_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many successful patient notifications have been sent across all channels.'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='notified_by_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='notified_by_email_by',
            field=models.ForeignKey(blank=True, help_text='Operator who sent the most recent successful email notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('COLLECTION_IN_PROGRESS', 'Collection In Progress'), ('IN_ANALYSIS', 'In Analysis'), ('AWAITING_REVIEW', 'Awaiting Review'), ('RETEST_REQUIRED', 'Retest Required'), ('READY_FOR_RELEASE', 'Ready For Release'), ('VALIDATED', 'Validated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25),
        ),
    ]
