# Generated by Django 4.2.17 on 2026-05-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_requests', '0018_split_closure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Operator who triggered the first patient-facing notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='reopen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('COLLECTION_IN_PROGRESS', 'Collection In Progress'), ('IN_ANALYSIS', 'In Analysis'), ('AWAITING_REVIEW', 'Awaiting Review'), ('RETEST_REQUIRED', 'Retest Required'), ('READY_FOR_RELEASE', 'Ready For Release'), ('VALIDATED', 'Validated'), ('RESULT_ISSUED', 'Result Issued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25),
        ),
    ]
