# Generated by Django 4.2.17 on 2026-05-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_requests', '0020_labelsequence_period_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlabel',
            name='barcode_value',
            field=models.CharField(db_index=True, help_text='Identifier printed on the label and scanned in workflow. Unique per batch in PER_FAMILY mode, shared across the batch in SAME_REQUEST_NUMBER mode (Phase 4 of the flexible-labels rollout).', max_length=64),
        ),
    ]
