# Generated by Django 4.2.17 on 2026-05-04 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_requests', '0021_alter_requestlabel_barcode_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlabelbatch',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Total successful PDF downloads. The mark-collected gate refuses when this is 0; > 0 means the labels reached the lab at least once.'),
        ),
        migrations.AddField(
            model_name='requestlabelbatch',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the FIRST successful PDF download. Stays pinned across re-downloads — the gate uses download_count for "ever downloaded?" checks; this field is the audit-grade first-touch.', null=True),
        ),
        migrations.AddField(
            model_name='requestlabelbatch',
            name='downloaded_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who first downloaded the PDF. SET_NULL on user deletion so the timestamp survives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_downloaded_label_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
