# Generated by Django 4.2.17 on 2026-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_requests', '0022_label_batch_download_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequestitem',
            name='parameter_ids_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Active ExamParameter ids at item creation time, as a list of UUID strings. Used by result-entry services to scope the parameter set to what existed when the item was made — adding a parameter later does NOT inject it into in-flight requests.'),
        ),
        migrations.AddField(
            model_name='analysisrequestitem',
            name='result_structure_snapshot',
            field=models.CharField(blank=True, default='', help_text='Result structure on the exam definition AT ITEM CREATION. Empty string on legacy rows; readers fall back to ``exam_definition.result_structure`` in that case.', max_length=20),
        ),
    ]
