"""
Cytova — Tenant URL Configuration
Served on all tenant subdomains: laba.cytova.io, labb.cytova.io, etc.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from apps.requests.patient_access_views import result_access, result_download, verify_password

urlpatterns = [
    # Django admin (accessible from tenant context in development)
    path('admin/', admin.site.urls),

    path('api/v1/', include([

        # ------------------------------------------------------------------
        # Authentication — custom views with audit logging + role claims
        # ------------------------------------------------------------------
        path('auth/', include('apps.authentication.urls')),

        # ------------------------------------------------------------------
        # Staff users + RBAC
        # ------------------------------------------------------------------
        path('users/', include('apps.users.urls')),

        # ------------------------------------------------------------------
        # API schema & docs (restrict access in production via settings)
        # ------------------------------------------------------------------
        path('schema/', SpectacularAPIView.as_view(), name='schema'),
        path('docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

        # ------------------------------------------------------------------
        # Domain modules
        # ------------------------------------------------------------------
        path('patients/',  include('apps.patients.urls')),
        path('catalog/',   include('apps.catalog.urls')),
        path('requests/',  include('apps.requests.urls')),
        path('results/',   include('apps.results.urls')),
        path('stock/',     include('apps.stock.urls')),
        # Procurement domain — unified supplier + purchase order + reception routing
        path('procurement/',  include('apps.procurement.urls')),
        # Legacy: /suppliers/ still available for backward compatibility
        path('suppliers/',    include('apps.suppliers.urls')),
        path('partners/',     include('apps.partners.urls')),
        path('invoicing/',    include('apps.invoicing.urls')),
        path('alerts/',       include('apps.alerts.urls')),
        path('dashboard/',    include('apps.dashboard.urls')),
        path('lab-settings/', include('apps.lab_settings.urls')),
        # path('audit/',        include('apps.audit.urls')),
        # path('files/',        include('apps.files.urls')),
        # path('portal/',       include('apps.portal.urls')),

    ])),

    # Public patient result access — no authentication, token is the credential
    path('r/<str:token>/', result_access, name='result-access'),
    path('r/<str:token>/verify-password/', verify_password, name='result-verify-password'),
    path('r/<str:token>/download/', result_download, name='result-download'),

    # Health check — returns {"status": "ok"}, no internal detail exposed
    path('health/', include('common.urls')),
]

# -----------------------------------------------------------------------------
# Development-only media serving
#
# In production, media files live in S3/MinIO and are served via pre-signed
# URLs generated by ``apps.files.signed_urls``. The backend never serves
# them directly. In development the fallback is Django's FileSystemStorage
# at ``MEDIA_ROOT``, and the browser requests them at ``MEDIA_URL`` — so the
# URL conf needs to route that prefix to Django's dev-only static view.
#
# ``static()`` is a deliberate no-op when DEBUG=False, so this entry is
# entirely inert in production and does not need a runtime guard here.
# -----------------------------------------------------------------------------
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
