"""
Cytova — Inventory Alert Models

InventoryAlert
    A condition-based record generated by periodic scans or on-demand checks.
    Four alert types cover the operational vocabulary:

        LOW_STOCK      — available quantity below the item's minimum_threshold
        OUT_OF_STOCK   — no available quantity across all lots
        EXPIRING_SOON  — lot expiry date within the configurable warning window
        EXPIRED        — lot past its expiry date

    Severity:
        CRITICAL   — OUT_OF_STOCK, EXPIRED  (immediate attention)
        WARNING    — LOW_STOCK, EXPIRING_SOON (action needed)
        INFO       — reserved for future advisory alerts

    Lifecycle:
        ACTIVE        — condition detected, not yet seen
        ACKNOWLEDGED  — user has seen the alert, condition still applies
        RESOLVED      — condition no longer applies (auto or manual)

    Duplicate prevention: at most one non-resolved alert per
    (alert_type, stock_item) for item-level alerts, and per
    (alert_type, stock_lot) for lot-level alerts, enforced by
    conditional UniqueConstraints.

    `title` and `message` are snapshot descriptions generated at creation
    time — they survive even if the related entity changes.
"""
from decimal import Decimal

from django.db import models
from django.db.models import Q

from common.models import BaseModel


class AlertType(models.TextChoices):
    LOW_STOCK     = 'LOW_STOCK',      'Low Stock'
    OUT_OF_STOCK  = 'OUT_OF_STOCK',   'Out of Stock'
    EXPIRING_SOON = 'EXPIRING_SOON',  'Expiring Soon'
    EXPIRED       = 'EXPIRED',        'Expired'


class AlertSeverity(models.TextChoices):
    CRITICAL = 'CRITICAL', 'Critical'
    WARNING  = 'WARNING',  'Warning'
    INFO     = 'INFO',     'Info'


class AlertStatus(models.TextChoices):
    ACTIVE       = 'ACTIVE',       'Active'
    ACKNOWLEDGED = 'ACKNOWLEDGED', 'Acknowledged'
    RESOLVED     = 'RESOLVED',     'Resolved'


# Map alert type → default severity
ALERT_SEVERITY_MAP = {
    AlertType.LOW_STOCK:     AlertSeverity.WARNING,
    AlertType.OUT_OF_STOCK:  AlertSeverity.CRITICAL,
    AlertType.EXPIRING_SOON: AlertSeverity.WARNING,
    AlertType.EXPIRED:       AlertSeverity.CRITICAL,
}

# Statuses that count as "open" (not yet resolved)
OPEN_STATUSES = frozenset({AlertStatus.ACTIVE, AlertStatus.ACKNOWLEDGED})


class InventoryAlert(BaseModel):
    alert_type = models.CharField(
        max_length=20,
        choices=AlertType.choices,
        db_index=True,
    )
    severity = models.CharField(
        max_length=10,
        choices=AlertSeverity.choices,
        db_index=True,
    )
    status = models.CharField(
        max_length=15,
        choices=AlertStatus.choices,
        default=AlertStatus.ACTIVE,
        db_index=True,
    )

    # ---- Related entities ----
    # Item-level alerts (LOW_STOCK, OUT_OF_STOCK): stock_item set, stock_lot null.
    # Lot-level alerts (EXPIRING_SOON, EXPIRED): both set (stock_item = lot.item).
    stock_item = models.ForeignKey(
        'stock.StockItem',
        on_delete=models.CASCADE,
        related_name='alerts',
        help_text='The stock item this alert refers to.',
    )
    stock_lot = models.ForeignKey(
        'stock.StockLot',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='alerts',
        help_text='Set for lot-level alerts (EXPIRING_SOON, EXPIRED).',
    )

    # ---- Snapshot ----
    title = models.CharField(max_length=255)
    message = models.TextField()
    threshold_value = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        null=True,
        blank=True,
        help_text='The threshold/limit at scan time (e.g. minimum_threshold).',
    )
    current_value = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        null=True,
        blank=True,
        help_text='The observed value at scan time (e.g. available qty, days to expiry).',
    )

    # ---- Resolution tracking ----
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    acknowledged_by = models.ForeignKey(
        'users.StaffUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='acknowledged_alerts',
    )
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(
        'users.StaffUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='resolved_alerts',
        help_text='Null when auto-resolved by scan.',
    )

    class Meta:
        verbose_name = 'Inventory Alert'
        verbose_name_plural = 'Inventory Alerts'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['status', 'severity']),
            models.Index(fields=['alert_type', 'status']),
            models.Index(fields=['stock_item', 'alert_type', 'status']),
        ]
        constraints = [
            # At most one open alert per (type, item) for item-level alerts
            models.UniqueConstraint(
                fields=['alert_type', 'stock_item'],
                condition=Q(
                    status__in=[AlertStatus.ACTIVE, AlertStatus.ACKNOWLEDGED],
                    stock_lot__isnull=True,
                ),
                name='unique_open_item_alert',
            ),
            # At most one open alert per (type, lot) for lot-level alerts
            models.UniqueConstraint(
                fields=['alert_type', 'stock_lot'],
                condition=Q(
                    status__in=[AlertStatus.ACTIVE, AlertStatus.ACKNOWLEDGED],
                    stock_lot__isnull=False,
                ),
                name='unique_open_lot_alert',
            ),
        ]

    def __str__(self):
        return f'[{self.severity}] {self.title}'
