# Generated by Django 4.2.17 on 2026-04-18 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0003_partnerorganization_invoice_discount_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_requests', '0014_public_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, help_text='Professional invoice number: INV-YYYYMM-NNNNNN.', max_length=25, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_rate_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Partner discount % snapshotted at generation.', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('pdf_file_key', models.CharField(blank=True, default='', help_text='Internal storage key for the rendered invoice PDF.', max_length=500)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number_snapshot', models.CharField(max_length=30)),
                ('public_reference_snapshot', models.CharField(max_length=20)),
                ('patient_display_name', models.CharField(max_length=255)),
                ('exam_code_snapshot', models.CharField(max_length=30)),
                ('exam_name_snapshot', models.CharField(max_length=255)),
                ('performed_date', models.DateField(blank=True, help_text='Date the exam was collected/performed.', null=True)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('billed_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('line_amount', models.DecimalField(decimal_places=2, help_text='Billed amount for this line (= billed_price_snapshot).', max_digits=12)),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'ordering': ['patient_display_name', 'performed_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Number Sequence',
                'verbose_name_plural': 'Invoice Number Sequences',
            },
        ),
        migrations.AddConstraint(
            model_name='invoicenumbersequence',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_invoice_seq_year_month'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='analysis_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='analysis_requests.analysisrequest'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='request_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='analysis_requests.analysisrequestitem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.partnerorganization'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'request_item'), name='unique_line_per_item_per_invoice'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['partner', '-generated_at'], name='invoicing_i_partner_653377_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-generated_at'], name='invoicing_i_status_2a46e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('partner', 'period_start', 'period_end'), name='unique_confirmed_invoice_per_partner_period'),
        ),
    ]
