# Generated by Django 4.2.17 on 2026-04-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT % snapshotted at generation.', max_digits=5),
        ),
    ]
