# Generated by Django 4.2.17 on 2026-04-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_subtotal_after_discount_invoice_vat_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='statement_file_key',
            field=models.CharField(blank=True, default='', help_text='Internal storage key for the rendered financial statement PDF.', max_length=500),
        ),
    ]
