# Generated by Django 4.2.17 on 2026-05-01 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_refactor_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cytova_identity_unlinked_at',
            field=models.DateTimeField(blank=True, help_text='When the link was last cleared. Survives a subsequent re-link so the audit trail is continuous; the link service stamps a fresh verified_at on relink.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytova_identity_unlinked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cytova_links_unlinked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytova_identity_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the link was created via the global identity verification service.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytova_identity_verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed the link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cytova_links_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytova_patient_account_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the global PatientAccount UUID at link time. NOT a foreign key — patient_portal tables live in the public schema. Validity is re-checked at use time.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytova_patient_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Snapshot of the global Cytova Patient ID (CV-XXXX-XXXX) once a verified link exists. Empty when the patient is not linked.', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('cytova_patient_id', ''), _negated=True), fields=('cytova_patient_id',), name='unique_patient_cytova_id_when_set'),
        ),
    ]
