# Generated by Django 4.2.17 on 2026-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_cytova_identity_unlinked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth_unknown',
            field=models.BooleanField(default=False, help_text='True when the lab confirms the DOB is unavailable. When true, ``date_of_birth`` may be null. When false, validators require ``date_of_birth`` to be set.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_number_auto_generated',
            field=models.BooleanField(default=False, help_text="True when ``document_number`` was auto-generated by the service (typically because the operator picked ``DocumentType.UNKNOWN`` and left the number blank). The UI uses this to render the value as a placeholder rather than a real ID — surfacing it as a real ID would mislead downstream operators and patients about the document's provenance."),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID_CARD', 'National ID Card'), ('PASSPORT', 'Passport'), ('CIP', 'CIP'), ('RESIDENCE_PERMIT', 'Residence Permit'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown / not provided')], default='NATIONAL_ID_CARD', max_length=20),
        ),
    ]
