# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('STAFF_USER', 'Staff User'), ('PATIENT_PORTAL', 'Patient Portal'), ('SYSTEM', 'System'), ('PLATFORM_ADMIN', 'Platform Admin')], db_index=True, max_length=20)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_email', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('VALIDATE', 'Validate'), ('PUBLISH', 'Publish'), ('CONFIRM', 'Confirm'), ('CANCEL', 'Cancel'), ('DEACTIVATE', 'Deactivate'), ('TOKEN_REVOKED', 'Token Revoked'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
