# Generated by Django 4.2.17 on 2026-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('VALIDATE', 'Validate'), ('SUBMIT', 'Submit'), ('PUBLISH', 'Publish'), ('CONFIRM', 'Confirm'), ('CANCEL', 'Cancel'), ('DEACTIVATE', 'Deactivate'), ('REACTIVATE', 'Reactivate'), ('TOKEN_REVOKED', 'Token Revoked'), ('PASSWORD_RESET', 'Password Reset'), ('ROLE_ASSIGN', 'Role Assign'), ('PERMISSION_OVERRIDE', 'Permission Override'), ('RESULT_ISSUED', 'Result Issued'), ('RESULT_REISSUED', 'Result Reissued'), ('RESULT_REOPENED', 'Result Reopened'), ('RESULT_SHARED_CYTOVA', 'Result Shared via Cytova'), ('CYTOVA_SHARE_REVOKED', 'Cytova Share Revoked'), ('PATIENT_CYTOVA_IDENTITY_LINKED', 'Patient Cytova Identity Linked'), ('PATIENT_CYTOVA_IDENTITY_UNLINKED', 'Patient Cytova Identity Unlinked')], db_index=True, max_length=40),
        ),
    ]
