"""
Cytova — Patient Portal models (global, public schema)

Three rows together describe one patient's portal identity:

  - ``PatientAccount``  — credentials + lifecycle state (login).
  - ``PatientProfile``  — human-readable profile + the global Cytova
                          Patient ID.
  - ``PatientConsent``  — append-only legal-acceptance record.

These tables intentionally live in the ``public`` schema and are NOT
installed in any lab tenant schema. See ``apps/patient_portal/__init__.py``
for the full architecture rationale.
"""
from __future__ import annotations

import uuid

from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from django.utils import timezone

from .managers import PatientAccountManager


class PatientAccount(AbstractBaseUser):
    """
    Global Cytova patient login. Email is the credential; password is
    hashed via Django's ``set_password`` (same KDF used everywhere else
    in the project).

    Notes
    -----
    - ``PermissionsMixin`` is intentionally omitted: patients do not
      carry Django auth groups / permissions, and pulling the mixin in
      would attach M2M tables to ``auth_*`` models we don't want
      coupled to a future dedicated schema.
    - This model is NOT ``AUTH_USER_MODEL`` (that role belongs to
      ``apps.users.StaffUser`` in tenant schemas). Patient
      authentication will use a dedicated auth backend keyed on
      ``email``; staff JWT auth is unaffected.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True, db_index=True)
    email_verified_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True, db_index=True)

    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    # ``last_login`` is provided by ``AbstractBaseUser``.

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS: list[str] = []

    objects = PatientAccountManager()

    class Meta:
        # Explicit table name keeps the public schema readable and
        # decouples the table identity from any future Django app
        # rename. The ``patient_portal_`` prefix matches the
        # forthcoming dedicated schema's namespace.
        db_table = 'patient_portal_account'
        verbose_name = 'Patient Account'
        verbose_name_plural = 'Patient Accounts'
        ordering = ['-created_at']

    def __str__(self) -> str:
        return f'PatientAccount<{self.email}>'

    # --- Helpers -----------------------------------------------------

    def mark_email_verified(self) -> None:
        """Idempotent — only writes when the row hasn't been verified yet."""
        if self.email_verified_at is None:
            self.email_verified_at = timezone.now()
            self.save(update_fields=['email_verified_at', 'updated_at'])


class PatientProfile(models.Model):
    """
    Human-readable identity tied to a portal account.

    The ``cytova_patient_id`` is the value patients share verbally with
    a lab receptionist or quote on a paper form — it must be unique,
    visually unambiguous (no 0/1/I/O), and short enough to dictate over
    a phone. Generated by
    ``apps.patient_portal.id_generator.generate_cytova_patient_id``.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    account = models.OneToOneField(
        PatientAccount,
        on_delete=models.CASCADE,
        related_name='profile',
    )
    cytova_patient_id = models.CharField(
        max_length=12,
        unique=True,
        db_index=True,
        help_text='Public-facing Cytova Patient ID (CV-XXXX-XXXX).',
    )

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    phone = models.CharField(max_length=50, blank=True, default='')

    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'patient_portal_profile'
        verbose_name = 'Patient Profile'
        verbose_name_plural = 'Patient Profiles'

    def __str__(self) -> str:
        return f'{self.cytova_patient_id} · {self.first_name} {self.last_name}'

    @property
    def full_name(self) -> str:
        return f'{self.first_name} {self.last_name}'.strip()


class PatientConsent(models.Model):
    """
    Append-only record of a patient's acceptance of the Terms of Service
    and Privacy Policy. Versions are snapshotted from settings at the
    moment of acceptance, so updates to the running settings never
    rewrite history.

    The IP address and user agent are recorded for audit-trail purposes
    (regulator inquiries about consent provenance). Rows are never
    updated or deleted in normal operation; renewing consent creates a
    new row.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    account = models.ForeignKey(
        PatientAccount,
        on_delete=models.CASCADE,
        related_name='consents',
    )
    terms_version = models.CharField(max_length=20)
    privacy_version = models.CharField(max_length=20)
    accepted_at = models.DateTimeField(default=timezone.now, db_index=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=500, blank=True, default='')

    class Meta:
        db_table = 'patient_portal_consent'
        verbose_name = 'Patient Consent'
        verbose_name_plural = 'Patient Consents'
        ordering = ['-accepted_at']
        indexes = [
            models.Index(fields=['account', '-accepted_at']),
        ]

    def __str__(self) -> str:
        return (
            f'Consent<{self.account_id} terms={self.terms_version} '
            f'privacy={self.privacy_version} at={self.accepted_at:%Y-%m-%d}>'
        )


class PatientEmailVerificationToken(models.Model):
    """
    Single-use email-verification token for a portal account.

    The plaintext token is sent to the patient via email and never
    persisted — only the SHA-256 hash is stored (via
    ``common.utils.crypto.hash_token``). On verification:

    - the row is matched by hash + ``is_used=False`` + ``expires_at > now``
    - ``account.email_verified_at`` is stamped
    - the consumed token is marked ``is_used=True`` + ``used_at``
    - any other outstanding tokens for the same account are invalidated

    Mirrors the staff-side ``apps.users.PasswordResetToken`` shape so
    the same hashing / single-use / IP-capture invariants apply.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    account = models.ForeignKey(
        PatientAccount,
        on_delete=models.CASCADE,
        related_name='email_verification_tokens',
    )
    token_hash = models.CharField(max_length=64, unique=True, db_index=True)
    created_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False, db_index=True)
    used_at = models.DateTimeField(null=True, blank=True)
    created_by_ip = models.GenericIPAddressField(null=True, blank=True)

    class Meta:
        db_table = 'patient_portal_email_verification_token'
        verbose_name = 'Patient Email Verification Token'
        verbose_name_plural = 'Patient Email Verification Tokens'
        indexes = [
            models.Index(fields=['account', 'is_used']),
        ]

    def __str__(self) -> str:
        return (
            f'PatientEmailVerificationToken<account={self.account_id} '
            f'used={self.is_used} expires={self.expires_at:%Y-%m-%d %H:%M}>'
        )


# ---------------------------------------------------------------------------
# Lab → patient sharing (snapshots, public schema)
# ---------------------------------------------------------------------------

class SharedResultSourceType(models.TextChoices):
    """Where the shared result originated. ``DIRECT`` means the lab ran
    the analysis themselves and is sharing the result with the patient.
    ``PARTNER`` means the request was received from a partner clinic /
    referring lab — captured separately so future analytics can split
    direct vs. partner-driven sharing without inferring it from text."""
    DIRECT = 'DIRECT', 'Direct'
    PARTNER = 'PARTNER', 'Partner'


class PatientSharedChannel(models.TextChoices):
    """Channel through which a result version reached the patient.

    Values map 1:1 to product flows:

    - ``CYTOVA``     — Notify Cytova (account-bound share, written here in
                       Phase 1).
    - ``EMAIL``      — Notify-by-email path that creates a portal-visible
                       version (reserved; no writer in Phase 1).
    - ``SHARE_LINK`` — Secure share link that materialises a portal entry
                       only when redeemed by an authenticated patient
                       (reserved; no writer in Phase 1).
    - ``MANUAL``     — Staff-driven manual share / backfill (reserved).

    Stored as a small text field rather than a numeric code so the
    audit/log surface stays human-readable. Empty string is permitted
    on legacy rows that pre-date this column — every new write goes
    through ``notify_cytova_service`` which always populates it.
    """
    CYTOVA = 'CYTOVA', 'Cytova'
    EMAIL = 'EMAIL', 'Email'
    SHARE_LINK = 'SHARE_LINK', 'Share link'
    MANUAL = 'MANUAL', 'Manual'


class SharedResultStatus(models.TextChoices):
    """Lifecycle of a shared-result row from the patient's point of view.

    ``ACTIVE``            — visible in the patient portal, downloadable.
    ``HIDDEN_BY_PATIENT`` — patient clicked "Remove from my space".
                            The row stays so the lab tenant retains
                            audit visibility, but it is excluded from
                            every patient-portal query and the file
                            download endpoint refuses to stream it.
    ``REVOKED``           — staff/admin revocation (e.g. wrong patient,
                            withdrawn share). Same effect on the
                            patient view as HIDDEN_BY_PATIENT but the
                            distinction is preserved for the audit
                            trail.
    """
    ACTIVE = 'ACTIVE', 'Active'
    HIDDEN_BY_PATIENT = 'HIDDEN_BY_PATIENT', 'Hidden by patient'
    REVOKED = 'REVOKED', 'Revoked'


class PatientSharedResult(models.Model):
    """
    Snapshot of a result a lab tenant has shared with a patient portal
    account. Lives in the public schema and intentionally has NO foreign
    key into any tenant model — see ``apps/patient_portal/__init__.py``
    for the full snapshot rationale. The lab tenant retains the
    canonical ``AnalysisRequest`` + ``AnalysisRequestReport`` rows in
    its own schema; this row is the patient-side view of "the lab said
    this result is mine".

    All fields are deliberately denormalised strings/dates: the lab
    name is captured at share time so a future tenant rename doesn't
    rewrite the patient's history; the request reference is what the
    patient should quote if they need to call the lab. Removing the
    underlying lab schema would not erase this record.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    patient_account = models.ForeignKey(
        PatientAccount,
        on_delete=models.CASCADE,
        related_name='shared_results',
    )
    source_type = models.CharField(
        max_length=10, choices=SharedResultSourceType.choices,
        default=SharedResultSourceType.DIRECT,
    )
    source_name = models.CharField(
        max_length=255,
        help_text='Snapshot of the lab name (or partner name) at share time.',
    )
    request_reference = models.CharField(
        max_length=64, blank=True, default='',
        help_text='Snapshot of the request public reference / number — '
                  'what the patient should quote when contacting the lab.',
    )
    request_date = models.DateField(null=True, blank=True)
    result_available_date = models.DateField(null=True, blank=True)
    created_by_lab = models.CharField(
        max_length=255, blank=True, default='',
        help_text='Optional snapshot of the staff member or lab identity '
                  'that initiated the share.',
    )
    status = models.CharField(
        max_length=20, choices=SharedResultStatus.choices,
        default=SharedResultStatus.ACTIVE, db_index=True,
    )
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    # ---- Immutable lab-side linkage ----
    # Captured at share time so the lab can later revoke its own
    # shares without taking a hard FK across schemas. ``source_*``
    # never changes after insert; updating here would silently rewrite
    # the patient's history, which the snapshot model exists to prevent.
    source_tenant_schema = models.CharField(
        max_length=64, blank=True, default='',
        help_text='Snapshot of the lab tenant schema name that produced '
                  'this share. Used by the lab-side revoke endpoint to '
                  'scope its lookup; never exposed to the patient.',
    )
    source_request_id = models.UUIDField(
        null=True, blank=True, db_index=True,
        help_text='Snapshot of the originating ``AnalysisRequest.id`` in '
                  'the lab tenant schema. Soft reference (no FK — the '
                  'tables live in different schemas).',
    )

    # ---- Patient-side activity counters (UX-friendly) ----
    first_viewed_at = models.DateTimeField(null=True, blank=True)
    last_downloaded_at = models.DateTimeField(null=True, blank=True)
    download_count = models.PositiveIntegerField(default=0)

    # ---- Revocation (lab side) ----
    revoked_at = models.DateTimeField(null=True, blank=True)
    revoked_by_lab = models.CharField(
        max_length=255, blank=True, default='',
        help_text='Snapshot of who/what triggered the revocation '
                  '(staff email or lab identity). Free text — the '
                  'patient never sees this.',
    )

    # ---- Notification status snapshot ----
    # Tri-state: '' (not attempted), 'SENT', 'FAILED'. Stays as a plain
    # string rather than a TextChoices to keep migrations cheap; the
    # set is small and stable enough to not justify the constant churn.
    email_notification_status = models.CharField(
        max_length=20, blank=True, default='',
    )
    email_notification_sent_at = models.DateTimeField(null=True, blank=True)

    # ---- Patient-facing report version metadata ----
    # The patient portal tracks a SEPARATE version line from the lab's
    # internal ``AnalysisRequestReport`` versions: a row exists here
    # only when the lab actively shared/notified that version. A lab
    # regenerating a report internally without sharing must NOT update
    # the patient's view — that invariant is enforced by the share
    # services (they are the only writers of these columns).
    #
    # ``report_version_number`` is the lab's internal version number
    # snapshotted at share time, kept here for traceability and the
    # patient-facing "Version N" badge. It is allowed to be NULL on
    # rows that pre-date this column — new writes always populate it.
    report_version_number = models.PositiveIntegerField(
        null=True, blank=True,
        help_text='Lab-side report version_number snapshotted at share time.',
    )
    report_generated_at = models.DateTimeField(
        null=True, blank=True,
        help_text='Snapshot of when the underlying lab report version was '
                  'generated. Distinct from ``shared_at`` because a version '
                  'may be generated long before it is actually shared.',
    )
    shared_at = models.DateTimeField(
        null=True, blank=True, db_index=True,
        help_text='When this version was actively shared/notified to the '
                  'patient. Coincides with ``created_at`` for new rows; '
                  'kept as a separate column so the patient versions API '
                  'has a semantic, channel-agnostic timestamp to expose.',
    )
    shared_channel = models.CharField(
        max_length=15, blank=True, default='',
        choices=PatientSharedChannel.choices,
        help_text='Which channel materialised this shared version. '
                  '``CYTOVA`` is the only writer in Phase 1.',
    )
    is_current_for_patient = models.BooleanField(
        default=True, db_index=True,
        help_text='True iff this is the latest version the lab shared with '
                  'this patient for this source request. Toggled to False '
                  'by the share service when a newer version is shared. '
                  'Independent of ``status`` — a row that is current for '
                  'the patient may still be REVOKED, in which case the '
                  'patient view filters it out anyway.',
    )

    class Meta:
        db_table = 'patient_portal_shared_result'
        verbose_name = 'Patient Shared Result'
        verbose_name_plural = 'Patient Shared Results'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['patient_account', '-created_at']),
        ]

    def __str__(self) -> str:
        return (
            f'PatientSharedResult<account={self.patient_account_id} '
            f'source={self.source_name!r} ref={self.request_reference!r}>'
        )


class PatientSharedResultFile(models.Model):
    """
    File reference attached to a ``PatientSharedResult``.

    The ``file_token`` is an opaque, non-guessable identifier the
    patient portal will quote to a future download endpoint — it does
    NOT reuse the lab's per-tenant ``ResultAccessToken`` (which is a
    different concept with a 48h TTL and is bound to a tenant patient
    record). The file itself is NOT physically duplicated yet; the
    download endpoint (out of scope for this step) will resolve the
    token to the original tenant storage key and stream from there.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    shared_result = models.ForeignKey(
        PatientSharedResult,
        on_delete=models.CASCADE,
        related_name='files',
    )
    file_token = models.CharField(
        max_length=64, unique=True, db_index=True, editable=False,
        help_text='Opaque random reference used by the future patient '
                  'portal download endpoint.',
    )
    filename = models.CharField(
        max_length=255,
        help_text='Suggested download filename for the patient browser.',
    )
    # ``storage_key`` is the lab-side snapshot — historically the only
    # storage reference the patient portal carried. Kept for back-compat
    # so older rows still resolve via the download endpoint's fallback
    # (see ``storage_origin`` below). New rows additionally populate
    # ``patient_storage_key`` with a portal-owned copy of the PDF so the
    # patient's access doesn't depend on lab-side storage lifecycle.
    storage_key = models.CharField(
        max_length=500, blank=True, default='',
        help_text='Snapshot of the LAB-side file storage key. Internal — '
                  'patients never see this. Used as a fallback when the '
                  'patient-side copy is unavailable (e.g. legacy rows '
                  'or copy-time failure).',
    )
    patient_storage_key = models.CharField(
        max_length=500, blank=True, default='',
        help_text='Path of the portal-owned copy of the PDF. Created at '
                  'share time via ``copy_file``. Always preferred by the '
                  'download endpoint over the lab-side snapshot.',
    )
    storage_origin = models.CharField(
        max_length=10,
        choices=[('LAB', 'Lab'), ('PATIENT', 'Patient')],
        default='LAB', db_index=True,
        help_text='Which storage location backs this row. ``PATIENT`` '
                  'means the file was successfully copied into the '
                  'patient portal storage; ``LAB`` means the patient is '
                  'still served from the original tenant location '
                  '(legacy rows or copy-failure fallback).',
    )
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'patient_portal_shared_result_file'
        verbose_name = 'Patient Shared Result File'
        verbose_name_plural = 'Patient Shared Result Files'

    def __str__(self) -> str:
        return f'PatientSharedResultFile<{self.filename}>'

    @property
    def effective_storage_key(self) -> str:
        """The storage key the download endpoint should actually open.
        Always prefers the patient-owned copy when present so a future
        lab-side cleanup never breaks the patient's access."""
        return self.patient_storage_key or self.storage_key


# ---------------------------------------------------------------------------
# Patient Portal audit log
# ---------------------------------------------------------------------------

class PatientPortalAuditAction(models.TextChoices):
    """Append-only event types written to ``PatientPortalAuditLog``.

    Distinct from the lab-tenant ``AuditAction`` enum so the patient
    audit surface can evolve independently — patients don't share the
    lab's set of staff workflow events, and we never want a tenant
    rename to drop unknown enum values from the patient audit
    history.
    """
    PATIENT_RESULT_SHARED = 'PATIENT_RESULT_SHARED', 'Result shared by lab'
    PATIENT_RESULT_DOWNLOADED = 'PATIENT_RESULT_DOWNLOADED', 'Result downloaded by patient'
    PATIENT_RESULT_HIDDEN_BY_PATIENT = 'PATIENT_RESULT_HIDDEN_BY_PATIENT', 'Result hidden by patient'
    PATIENT_RESULT_REVOKED_BY_LAB = 'PATIENT_RESULT_REVOKED_BY_LAB', 'Share revoked by lab'
    # Version-aware events. The legacy ``PATIENT_RESULT_SHARED`` is
    # still emitted on every share for back-compat with existing audit
    # readers; the two events below carry the version-line semantics
    # so a new reader can reconstruct "which version is current for
    # this patient?" without inspecting the snapshot row directly.
    PATIENT_VERSION_SHARED = 'PATIENT_VERSION_SHARED', 'Version shared with patient'
    PATIENT_VERSION_SUPERSEDED = 'PATIENT_VERSION_SUPERSEDED', 'Earlier shared version superseded'


class PatientPortalAuditLog(models.Model):
    """Append-only event log for the global patient portal.

    Lives in the public schema (not in any lab tenant). Distinct from
    the per-tenant ``apps.audit.AuditLog`` because the events recorded
    here belong to the global patient identity, not to a single lab —
    a patient-side download, hide, or share-revocation is meaningful
    across labs. The tenant audit log still gets its own row when
    appropriate (e.g. revoke writes both).

    Safety contract for ``metadata`` values
    --------------------------------------
    Callers MUST NOT include in the metadata dict:
      - PDF storage keys / URLs / file paths
      - download tokens or any opaque secret
      - patient PII (name, DOB, email, phone)
      - clinical / medical content

    Only IDs already known to both sides (``shared_result_id``,
    ``file_id``, ``source_request_reference``) plus public counters are
    safe. The ``apps.patient_portal.audit`` helper enforces a small
    set of allowed keys for each action.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    patient_account = models.ForeignKey(
        PatientAccount,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='audit_events',
        help_text='Set null on account deletion so the audit row '
                  'survives — needed for forensic continuity even when '
                  'the actor account is gone.',
    )
    action = models.CharField(
        max_length=40, choices=PatientPortalAuditAction.choices, db_index=True,
    )
    entity_type = models.CharField(max_length=64)
    entity_id = models.UUIDField(null=True, blank=True, db_index=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=500, blank=True, default='')
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        db_table = 'patient_portal_audit_log'
        verbose_name = 'Patient Portal Audit Log'
        verbose_name_plural = 'Patient Portal Audit Logs'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['patient_account', '-created_at']),
            models.Index(fields=['action', '-created_at']),
        ]

    def __str__(self) -> str:
        return (
            f'PatientPortalAuditLog<{self.action} '
            f'patient={self.patient_account_id} at={self.created_at:%Y-%m-%d %H:%M}>'
        )


# ---------------------------------------------------------------------------
# Patient Portal token tracking (parallel to simplejwt's per-tenant
# OutstandingToken / BlacklistedToken machinery)
# ---------------------------------------------------------------------------

class PatientTokenType(models.TextChoices):
    """``access`` / ``refresh`` mirror the simplejwt token classes so a
    log query can split the two trivially."""
    ACCESS = 'ACCESS', 'Access'
    REFRESH = 'REFRESH', 'Refresh'


class PatientOutstandingToken(models.Model):
    """One row per token we issue to a patient. Indexed on ``jti`` so
    the auth backend can resolve in O(1) on every authenticated
    request.

    We deliberately store ONLY the JWT ID (``jti``) — never the full
    token, never the signature. The plaintext token lives in the
    patient's browser; this row exists purely to gate the JTI behind
    a blacklist check on every request and to support session-wide
    revocation (logout-all, password change).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    patient_account = models.ForeignKey(
        PatientAccount,
        on_delete=models.CASCADE,
        related_name='outstanding_tokens',
    )
    jti = models.CharField(
        max_length=64, unique=True, db_index=True,
        help_text='JWT ID claim — the only durable identifier we '
                  'store. Compared against the ``jti`` in the bearer '
                  'token on every request.',
    )
    token_type = models.CharField(
        max_length=10, choices=PatientTokenType.choices,
    )
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    expires_at = models.DateTimeField(db_index=True)
    user_agent = models.CharField(max_length=500, blank=True, default='')
    ip_address = models.GenericIPAddressField(null=True, blank=True)

    class Meta:
        db_table = 'patient_portal_outstanding_token'
        verbose_name = 'Patient Outstanding Token'
        verbose_name_plural = 'Patient Outstanding Tokens'
        indexes = [
            # Compound index supports the per-account lookup the
            # logout-all + password-change paths use, and lets a
            # cleanup query prune by expiry without scanning the
            # whole table.
            models.Index(fields=['patient_account', 'expires_at']),
        ]

    def __str__(self) -> str:
        return (
            f'PatientOutstandingToken<{self.token_type} '
            f'patient={self.patient_account_id} jti=…{self.jti[-6:]}>'
        )


class PatientBlacklistedToken(models.Model):
    """Marks an outstanding token as revoked. The auth backend
    rejects any token whose Outstanding row has a corresponding
    Blacklisted row.

    Modelled as a ``OneToOneField`` so the auth backend can resolve
    "is this token blacklisted?" in a single ``select_related`` join
    rather than a follow-up SELECT.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    token = models.OneToOneField(
        PatientOutstandingToken,
        on_delete=models.CASCADE,
        related_name='blacklist',
    )
    blacklisted_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'patient_portal_blacklisted_token'
        verbose_name = 'Patient Blacklisted Token'
        verbose_name_plural = 'Patient Blacklisted Tokens'

    def __str__(self) -> str:
        return f'PatientBlacklistedToken<token={self.token_id}>'
