# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Exam Category',
                'verbose_name_plural': 'Exam Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sample_type', models.CharField(choices=[('BLOOD', 'Blood'), ('URINE', 'Urine'), ('STOOL', 'Stool'), ('CSF', 'Cerebrospinal Fluid'), ('SWAB', 'Swab'), ('SALIVA', 'Saliva'), ('TISSUE', 'Tissue'), ('OTHER', 'Other')], db_index=True, max_length=10)),
                ('turnaround_hours', models.PositiveIntegerField(blank=True, help_text='Expected hours from sample receipt to result. Overridable per lab via LabExamSettings.', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Exam Definition',
                'verbose_name_plural': 'Exam Definitions',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabExamSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_range', models.CharField(blank=True, default='', help_text='Lab-specific normal range, e.g. "3.5–5.0 mmol/L".', max_length=100)),
                ('turnaround_hours_override', models.PositiveIntegerField(blank=True, help_text='Overrides exam_definition.turnaround_hours for this lab.', null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text="Set to False to hide this exam from this lab's ordering workflow.")),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Exam Settings',
                'verbose_name_plural': 'Lab Exam Settings',
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('billed_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('insurance_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['-effective_from'],
            },
        ),
    ]
