# Generated by Django 4.2.17 on 2026-03-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pricing_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='exam_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='catalog.examdefinition'),
        ),
        migrations.AddField(
            model_name='labexamsettings',
            name='exam_definition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_settings', to='catalog.examdefinition'),
        ),
        migrations.AddField(
            model_name='labexamsettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examdefinition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='catalog.examcategory'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['exam_definition', 'effective_from'], name='catalog_pri_exam_de_942a8d_idx'),
        ),
    ]
