# Generated by Django 4.2.17 on 2026-03-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_refactor_pricing_rules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='catalog_pri_exam_de_7e5d8c_idx',
            old_name='catalog_pri_exam_de_active_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='catalog_pri_partner_06924b_idx',
            old_name='catalog_pri_partner_active_idx',
        ),
    ]
