# Generated by Django 4.2.17 on 2026-04-09 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('catalog', '0005_exam_metadata_enrichment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examdefinition',
            options={'ordering': ['family__display_order', 'name'], 'verbose_name': 'Exam Definition', 'verbose_name_plural': 'Exam Definitions'},
        ),
        migrations.AlterField(
            model_name='examdefinition',
            name='turnaround_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Expected hours from sample receipt to result.', null=True),
        ),
        migrations.AlterField(
            model_name='examfamily',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examsubfamily',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examtechnique',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='labexamsettings',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='labexamsettings',
            name='reference_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='labexamsettings',
            name='turnaround_hours_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='partners.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tubetype',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
