# Generated by Django 4.2.17 on 2026-04-12 22:29

from django.db import migrations


def backfill_null_techniques(apps, schema_editor):
    """Assign a sentinel technique to exam definitions with null technique."""
    ExamTechnique = apps.get_model('catalog', 'ExamTechnique')
    ExamDefinition = apps.get_model('catalog', 'ExamDefinition')

    null_count = ExamDefinition.objects.filter(technique__isnull=True).count()
    if null_count == 0:
        return

    sentinel, _ = ExamTechnique.objects.get_or_create(
        name='Unspecified',
        defaults={'description': 'Auto-assigned to exams that had no technique set.', 'is_active': True},
    )
    ExamDefinition.objects.filter(technique__isnull=True).update(technique=sentinel)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_exam_result_structure'),
    ]

    operations = [
        migrations.RunPython(backfill_null_techniques, migrations.RunPython.noop),
    ]
