# Generated by Django 4.2.17 on 2026-04-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_backfill_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdefinition',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='catalog.examtechnique'),
        ),
    ]
