"""
Cytova — Analysis Request Models

AnalysisRequest
    A lab work order for a single patient. Lives in DRAFT until confirmed by
    reception. Confirmation snapshots prices and locks the item list.
    Hard delete is blocked — requests are medical records.

AnalysisRequestItem
    One exam line within a request. Carries execution metadata (mode, partner,
    rejection reason) and snapshotted prices (unit + billed) at confirmation.
    Hard delete is blocked at the model level; service layer removes items from
    DRAFT requests via queryset.delete().

ExamTraceability
    Mandatory companion to every AnalysisRequestItem (created in the same
    transaction). Tracks sample receipt, processing start, and completion,
    together with who performed the analysis.
"""
import uuid

from django.db import models
from django.utils import timezone

from common.models import BaseModel


# ---------------------------------------------------------------------------
# Choice enumerations
# ---------------------------------------------------------------------------

class RequestStatus(models.TextChoices):
    DRAFT       = 'DRAFT',       'Draft'
    CONFIRMED   = 'CONFIRMED',   'Confirmed'
    IN_PROGRESS = 'IN_PROGRESS', 'In Progress'
    COMPLETED   = 'COMPLETED',   'Completed'
    CANCELLED   = 'CANCELLED',   'Cancelled'


class ItemStatus(models.TextChoices):
    PENDING     = 'PENDING',     'Pending'
    IN_PROGRESS = 'IN_PROGRESS', 'In Progress'
    COMPLETED   = 'COMPLETED',   'Completed'
    REJECTED    = 'REJECTED',    'Rejected'


class ExecutionMode(models.TextChoices):
    INTERNAL      = 'INTERNAL',      'Internal'
    SUBCONTRACTED = 'SUBCONTRACTED', 'Subcontracted'
    REJECTED      = 'REJECTED',      'Rejected'


# ---------------------------------------------------------------------------
# AnalysisRequest
# ---------------------------------------------------------------------------

class AnalysisRequest(BaseModel):
    """
    A lab work order: one patient → one or more exam items.

    Lifecycle: DRAFT → CONFIRMED → IN_PROGRESS → COMPLETED
                     └─────────────────────────→ CANCELLED

    request_number is auto-generated by the service after the first save
    (format: REQ-{YYYY}-{8-char UUID prefix}).
    """
    request_number = models.CharField(
        max_length=30,
        unique=True,
        db_index=True,
        blank=True,
        default='',
        help_text='Auto-generated human-readable identifier.',
    )
    patient = models.ForeignKey(
        'patients.Patient',
        on_delete=models.PROTECT,
        related_name='analysis_requests',
    )
    status = models.CharField(
        max_length=20,
        choices=RequestStatus.choices,
        default=RequestStatus.DRAFT,
        db_index=True,
    )
    notes = models.TextField(blank=True, default='')

    confirmed_at = models.DateTimeField(null=True, blank=True)
    confirmed_by = models.ForeignKey(
        'users.StaffUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='confirmed_requests',
    )
    cancelled_at = models.DateTimeField(null=True, blank=True)
    cancelled_by = models.ForeignKey(
        'users.StaffUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='cancelled_requests',
    )
    created_by = models.ForeignKey(
        'users.StaffUser',
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_analysis_requests',
    )

    class Meta:
        verbose_name = 'Analysis Request'
        verbose_name_plural = 'Analysis Requests'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['patient', 'status']),
            models.Index(fields=['status', 'created_at']),
        ]

    def __str__(self):
        return f'{self.request_number} — {self.patient} [{self.status}]'

    def delete(self, *args, **kwargs):
        """Analysis requests are medical records and cannot be hard-deleted."""
        raise PermissionError(
            'Analysis requests cannot be deleted. Cancel instead.'
        )


# ---------------------------------------------------------------------------
# AnalysisRequestItem
# ---------------------------------------------------------------------------

class AnalysisRequestItem(BaseModel):
    """
    One exam line within an analysis request.

    Prices (unit_price, billed_price) are NULL in DRAFT and snapshotted from
    the active PricingRule at confirmation. pricing_rule is a soft FK — kept
    for traceability even if the rule is later closed.

    Items with execution_mode=REJECTED are auto-transitioned to status=REJECTED
    at request confirmation and receive zero prices.

    Note: although SUBCONTRACTED is a valid execution_mode for record-keeping,
    there is no active inter-laboratory workflow — all processing is internal.
    """
    analysis_request = models.ForeignKey(
        AnalysisRequest,
        on_delete=models.CASCADE,
        related_name='items',
    )
    exam_definition = models.ForeignKey(
        'catalog.ExamDefinition',
        on_delete=models.PROTECT,
        related_name='request_items',
    )
    status = models.CharField(
        max_length=20,
        choices=ItemStatus.choices,
        default=ItemStatus.PENDING,
        db_index=True,
    )
    execution_mode = models.CharField(
        max_length=20,
        choices=ExecutionMode.choices,
        default=ExecutionMode.INTERNAL,
        db_index=True,
    )
    rejection_reason = models.TextField(blank=True, default='')
    external_partner_name = models.CharField(max_length=255, blank=True, default='')
    notes = models.TextField(blank=True, default='')

    # Snapshotted at confirmation — NULL before that point
    unit_price = models.DecimalField(
        max_digits=12, decimal_places=4, null=True, blank=True,
    )
    billed_price = models.DecimalField(
        max_digits=12, decimal_places=4, null=True, blank=True,
    )
    pricing_rule = models.ForeignKey(
        'catalog.PricingRule',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='item_snapshots',
    )

    class Meta:
        verbose_name = 'Analysis Request Item'
        verbose_name_plural = 'Analysis Request Items'
        ordering = ['created_at']
        constraints = [
            models.UniqueConstraint(
                fields=['analysis_request', 'exam_definition'],
                name='unique_exam_per_request',
            )
        ]

    def __str__(self):
        return (
            f'{self.analysis_request.request_number} / '
            f'{self.exam_definition.code} [{self.status}]'
        )

    def delete(self, *args, **kwargs):
        """Hard delete blocked. Service layer uses queryset.delete() for DRAFT removal."""
        raise PermissionError(
            'Analysis request items cannot be hard-deleted directly. '
            'Remove them from the draft request via the service layer.'
        )


# ---------------------------------------------------------------------------
# ExamTraceability
# ---------------------------------------------------------------------------

class ExamTraceability(models.Model):
    """
    Mandatory per-item traceability record.

    Created in the same transaction as the AnalysisRequestItem (CLAUDE.md
    constraint). All timestamps are NULL until the corresponding processing
    step occurs. Provides a complete audit trail for each exam performed.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    item = models.OneToOneField(
        AnalysisRequestItem,
        on_delete=models.CASCADE,
        related_name='traceability',
    )

    # Populated when item transitions PENDING → IN_PROGRESS
    sample_received_at = models.DateTimeField(null=True, blank=True)
    sample_received_by = models.ForeignKey(
        'users.StaffUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='received_samples',
    )

    # Populated when item transitions IN_PROGRESS → COMPLETED
    analysis_completed_at = models.DateTimeField(null=True, blank=True)
    performed_by = models.ForeignKey(
        'users.StaffUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='performed_analyses',
    )

    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Exam Traceability'
        verbose_name_plural = 'Exam Traceability Records'

    def __str__(self):
        return f'Traceability for {self.item}'
